package com.zstream.android.theme

import androidx.compose.ui.graphics.Color

object DefaultTheme {
    private val black = mapOf(
        "c50" to Color(0xFF000000),
        "c75" to Color(0xFF030303),
        "c80" to Color(0xFF080808),
        "c100" to Color(0xFF0d0d0d),
        "c125" to Color(0xFF141414),
        "c150" to Color(0xFF1a1a1a),
        "c200" to Color(0xFF262626),
        "c250" to Color(0xFF333333),
    )
    private val white = Color(0xFFFFFFFF)
    private val semantic = mapOf(
        "red" to mapOf(
            "c100" to Color(0xFFF46E6E),
            "c200" to Color(0xFFE44F4F),
            "c300" to Color(0xFFD74747),
            "c400" to Color(0xFFB43434),
        ),
        "green" to mapOf(
            "c100" to Color(0xFF60D26A),
            "c200" to Color(0xFF40B44B),
            "c300" to Color(0xFF31A33C),
            "c400" to Color(0xFF237A2B),
        ),
        "silver" to mapOf(
            "c100" to Color(0xFFDEDEDE),
            "c200" to Color(0xFFB6CAD7),
            "c300" to Color(0xFF8EA3B0),
            "c400" to Color(0xFF617A8A),
        ),
        "yellow" to mapOf(
            "c100" to Color(0xFFFFF599),
            "c200" to Color(0xFFFCEC61),
            "c300" to Color(0xFFD8C947),
            "c400" to Color(0xFFAFA349),
        ),
        "rose" to mapOf(
            "c100" to Color(0xFFDB3D61),
            "c200" to Color(0xFF8A293B),
            "c300" to Color(0xFF812435),
            "c400" to Color(0xFF701B2B),
        ),
    )
    private val blue = mapOf(
        "c50" to Color(0xFFccccd6),
        "c100" to Color(0xFFa2a2a2),
        "c200" to Color(0xFF868686),
        "c300" to Color(0xFF646464),
        "c400" to Color(0xFF4e4e4e),
        "c500" to Color(0xFF383838),
        "c600" to Color(0xFF2e2e2e),
        "c700" to Color(0xFF272727),
        "c800" to Color(0xFF181818),
        "c900" to Color(0xFF0f0f0f),
    )
    private val purple = mapOf(
        "c50" to Color(0xFFaaafff),
        "c100" to Color(0xFF8288fe),
        "c200" to Color(0xFF5a62eb),
        "c300" to Color(0xFF454cd4),
        "c400" to Color(0xFF333abe),
        "c500" to Color(0xFF292d86),
        "c600" to Color(0xFF1f2363),
        "c700" to Color(0xFF191b4a),
        "c800" to Color(0xFF111334),
        "c900" to Color(0xFF0b0d22),
    )
    private val ash = mapOf(
        "c50" to Color(0xFF8d8d8d),
        "c100" to Color(0xFF6b6b6b),
        "c200" to Color(0xFF545454),
        "c300" to Color(0xFF3c3c3c),
        "c400" to Color(0xFF313131),
        "c500" to Color(0xFF2c2c2c),
        "c600" to Color(0xFF252525),
        "c700" to Color(0xFF1e1e1e),
        "c800" to Color(0xFF181818),
        "c900" to Color(0xFF111111),
    )
    private val shade = mapOf(
        "c25" to Color(0xFF939393),
        "c50" to Color(0xFF7c7c7c),
        "c100" to Color(0xFF666666),
        "c200" to Color(0xFF4f4f4f),
        "c300" to Color(0xFF404040),
        "c400" to Color(0xFF343434),
        "c500" to Color(0xFF282828),
        "c600" to Color(0xFF202020),
        "c700" to Color(0xFF1a1a1a),
        "c800" to Color(0xFF151515),
        "c900" to Color(0xFF0e0e0e),
    )

    fun create(): ZStreamTheme = ZStreamTheme(
        id = "default",
        name = "Default",
        colors = ThemeColors(
            themePreview = ThemePreview(
                primary = black["c80"]!!,
                secondary = black["c100"]!!,
                ghost = white,
            ),
            pill = Pill(
                background = black["c100"]!!,
                backgroundHover = black["c125"]!!,
                highlight = blue["c200"]!!,
                activeBackground = shade["c700"]!!,
            ),
            global = Global(
                accentA = blue["c200"]!!,
                accentB = blue["c300"]!!,
            ),
            lightBar = LightBar(light = purple["c800"]!!),
            buttons = Buttons(
                toggle = purple["c300"]!!,
                toggleDisabled = black["c200"]!!,
                danger = semantic["rose"]!!["c300"]!!,
                dangerHover = semantic["rose"]!!["c200"]!!,
                secondary = black["c100"]!!,
                secondaryText = semantic["silver"]!!["c300"]!!,
                secondaryHover = black["c150"]!!,
                primary = white,
                primaryText = black["c50"]!!,
                primaryHover = semantic["silver"]!!["c100"]!!,
                purple = purple["c600"]!!,
                purpleHover = purple["c400"]!!,
                cancel = black["c100"]!!,
                cancelHover = black["c150"]!!,
            ),
            background = Background(
                main = black["c75"]!!,
                secondary = black["c75"]!!,
                secondaryHover = black["c75"]!!,
                accentA = purple["c600"]!!,
                accentB = black["c100"]!!,
            ),
            modal = Modal(background = shade["c800"]!!),
            type = Type(
                logo = purple["c100"]!!,
                emphasis = white,
                text = shade["c50"]!!,
                dimmed = shade["c50"]!!,
                divider = ash["c500"]!!,
                secondary = ash["c100"]!!,
                danger = semantic["red"]!!["c100"]!!,
                success = semantic["green"]!!["c100"]!!,
                link = purple["c100"]!!,
                linkHover = purple["c50"]!!,
            ),
            search = Search(
                background = black["c100"]!!,
                hoverBackground = shade["c900"]!!,
                focused = black["c125"]!!,
                placeholder = shade["c200"]!!,
                icon = shade["c500"]!!,
                text = white,
            ),
            mediaCard = MediaCard(
                hoverBackground = shade["c900"]!!,
                hoverAccent = black["c250"]!!,
                hoverShadow = black["c50"]!!,
                shadow = shade["c800"]!!,
                barColor = ash["c200"]!!,
                barFillColor = purple["c100"]!!,
                badge = shade["c700"]!!,
                badgeText = ash["c100"]!!,
            ),
            largeCard = LargeCard(
                background = black["c100"]!!,
                icon = purple["c400"]!!,
            ),
            dropdown = Dropdown(
                background = black["c100"]!!,
                altBackground = black["c80"]!!,
                hoverBackground = black["c150"]!!,
                highlight = semantic["yellow"]!!["c400"]!!,
                highlightHover = semantic["yellow"]!!["c200"]!!,
                text = shade["c50"]!!,
                secondary = shade["c100"]!!,
                border = shade["c400"]!!,
                contentBackground = black["c50"]!!,
            ),
            authentication = Authentication(
                border = shade["c300"]!!,
                inputBg = black["c100"]!!,
                inputBgHover = black["c150"]!!,
                wordBackground = shade["c500"]!!,
                copyText = shade["c100"]!!,
                copyTextHover = ash["c50"]!!,
                errorText = semantic["rose"]!!["c100"]!!,
            ),
            settings = Settings(
                sidebar = SettingsSidebar(
                    activeLink = black["c100"]!!,
                    badge = shade["c900"]!!,
                    type = SettingsSidebarType(
                        secondary = shade["c200"]!!,
                        inactive = shade["c50"]!!,
                        icon = black["c200"]!!,
                        iconActivated = purple["c200"]!!,
                        activated = purple["c100"]!!,
                    ),
                ),
                card = SettingsCard(
                    border = shade["c700"]!!,
                    background = black["c100"]!!,
                    altBackground = black["c100"]!!,
                ),
                saveBar = SettingsSaveBar(background = black["c50"]!!),
            ),
            utils = Utils(divider = ash["c300"]!!),
            onboarding = Onboarding(
                bar = shade["c400"]!!,
                barFilled = purple["c300"]!!,
                divider = shade["c200"]!!,
                card = shade["c800"]!!,
                cardHover = shade["c700"]!!,
                border = shade["c600"]!!,
                good = purple["c100"]!!,
                best = semantic["yellow"]!!["c100"]!!,
                link = purple["c100"]!!,
            ),
            errors = Errors(
                card = black["c75"]!!,
                border = ash["c500"]!!,
                type = ErrorsType(secondary = ash["c100"]!!),
            ),
            about = About(
                circle = black["c100"]!!,
                circleText = ash["c50"]!!,
            ),
            editBadge = EditBadge(
                bg = ash["c500"]!!,
                bgHover = ash["c400"]!!,
                text = ash["c50"]!!,
            ),
            progress = Progress(
                background = ash["c50"]!!,
                preloaded = ash["c50"]!!,
                filled = purple["c200"]!!,
            ),
            video = Video(
                buttonBackground = ash["c600"]!!,
                autoPlay = VideoAutoPlay(
                    background = ash["c800"]!!,
                    hover = ash["c600"]!!,
                ),
                scraping = VideoScraping(
                    card = black["c50"]!!,
                    error = semantic["red"]!!["c200"]!!,
                    success = semantic["green"]!!["c200"]!!,
                    loading = purple["c200"]!!,
                    noresult = black["c200"]!!,
                ),
                audio = VideoAudio(set = purple["c200"]!!),
                context = VideoContext(
                    background = black["c50"]!!,
                    light = shade["c50"]!!,
                    border = ash["c600"]!!,
                    hoverColor = ash["c600"]!!,
                    buttonFocus = ash["c500"]!!,
                    flagBg = ash["c500"]!!,
                    inputBg = black["c100"]!!,
                    buttonOverInputHover = ash["c500"]!!,
                    inputPlaceholder = ash["c200"]!!,
                    cardBorder = ash["c700"]!!,
                    slider = black["c200"]!!,
                    sliderFilled = purple["c200"]!!,
                    error = semantic["red"]!!["c200"]!!,
                    buttons = VideoContextButtons(
                        list = ash["c700"]!!,
                        active = ash["c900"]!!,
                    ),
                    closeHover = ash["c800"]!!,
                    type = VideoContextType(
                        main = semantic["silver"]!!["c300"]!!,
                        secondary = ash["c200"]!!,
                        accent = purple["c200"]!!,
                    ),
                ),
            ),
        ),
    )
}
