package com.zstream.android.theme

import androidx.compose.ui.graphics.Color

private data class PaletteThemeSpec(
    val id: String,
    val name: String,
    val purple: Map<String, Color>,
    val shade: Map<String, Color>,
    val ash: Map<String, Color>,
    val blue: Map<String, Color>,
)

private data class AccentDarkThemeSpec(
    val id: String,
    val name: String,
    val purple: Map<String, Color>,
    val previewSecondary: Color,
    val lightBar: Color,
)

private data class ClassicThemeSpec(
    val id: String,
    val name: String,
    val blue: Map<String, Color>,
    val purple: Map<String, Color>,
    val ash: Map<String, Color>,
    val shade: Map<String, Color>,
    val previewSecondary: Color,
    val previewGhost: Color,
    val globalAccentA: Color,
    val lightBar: Color,
    val mediaHoverBackground: Color,
    val mediaHoverAccent: Color,
    val mediaHoverShadow: Color,
    val mediaShadow: Color,
)

object ThemePresets {
    val builtInThemes: List<ZStreamTheme> = listOf(
        createPaletteTheme(
            PaletteThemeSpec(
                id = "teal",
                name = "Teal",
                purple = mapOf(
                    "c50" to color("#aad7ff"),
                    "c100" to color("#82c4ff"),
                    "c200" to color("#59a8ec"),
                    "c300" to color("#4491d6"),
                    "c400" to color("#317dbf"),
                    "c500" to color("#285b87"),
                ),
                shade = mapOf(
                    "c25" to color("#5db3a8"),
                    "c50" to color("#677c90"),
                    "c100" to color("#52667a"),
                    "c200" to color("#3f4f60"),
                    "c300" to color("#32404f"),
                    "c400" to color("#273441"),
                    "c500" to color("#1e2832"),
                    "c600" to color("#172028"),
                    "c700" to color("#131a22"),
                    "c800" to color("#0f151b"),
                    "c900" to color("#0a0e12"),
                ),
                ash = mapOf(
                    "c50" to color("#7f9b9b"),
                    "c100" to color("#5b7b7b"),
                    "c200" to color("#446463"),
                    "c300" to color("#2b4e4d"),
                    "c400" to color("#204241"),
                    "c500" to color("#1c3c3b"),
                    "c600" to color("#173232"),
                    "c700" to color("#132929"),
                    "c800" to color("#102020"),
                    "c900" to color("#0c1615"),
                ),
                blue = mapOf(
                    "c200" to color("#5dae8b"),
                    "c300" to color("#3b8c69"),
                    "c400" to color("#2a7152"),
                    "c500" to color("#1f503b"),
                ),
            ),
        ),
        createPaletteTheme(
            PaletteThemeSpec(
                id = "blue",
                name = "Blue",
                purple = mapOf(
                    "c50" to color("#aac5ff"),
                    "c100" to color("#82a9ff"),
                    "c200" to color("#4681ff"),
                    "c300" to color("#1a63ff"),
                    "c400" to color("#054eec"),
                    "c500" to color("#083aa7"),
                ),
                shade = mapOf(
                    "c25" to color("#5d7db3"),
                    "c50" to color("#756790"),
                    "c100" to color("#60527a"),
                    "c200" to color("#4a3f60"),
                    "c300" to color("#3c324f"),
                    "c400" to color("#302741"),
                    "c500" to color("#251e32"),
                    "c600" to color("#1d1728"),
                    "c700" to color("#181322"),
                    "c800" to color("#130f1b"),
                    "c900" to color("#0d0a12"),
                ),
                ash = mapOf(
                    "c50" to color("#7f859b"),
                    "c100" to color("#5b627b"),
                    "c200" to color("#444b64"),
                    "c300" to color("#2b344e"),
                    "c400" to color("#202842"),
                    "c500" to color("#1c243c"),
                    "c600" to color("#171d32"),
                    "c700" to color("#131829"),
                    "c800" to color("#101420"),
                    "c900" to color("#0c0f16"),
                ),
                blue = mapOf(
                    "c200" to color("#5d65ae"),
                    "c300" to color("#3b438c"),
                    "c400" to color("#2a3171"),
                    "c500" to color("#1f2450"),
                ),
            ),
        ),
        createPaletteTheme(
            PaletteThemeSpec(
                id = "gray",
                name = "Gray",
                purple = mapOf(
                    "c50" to color("#aaafff"),
                    "c100" to color("#8288fe"),
                    "c200" to color("#5a62eb"),
                    "c300" to color("#454cd4"),
                    "c400" to color("#333abe"),
                    "c500" to color("#292d86"),
                ),
                shade = mapOf(
                    "c25" to color("#9c9c9c"),
                    "c50" to color("#7c7c7c"),
                    "c100" to color("#666666"),
                    "c200" to color("#4f4f4f"),
                    "c300" to color("#404040"),
                    "c400" to color("#343434"),
                    "c500" to color("#282828"),
                    "c600" to color("#202020"),
                    "c700" to color("#1a1a1a"),
                    "c800" to color("#151515"),
                    "c900" to color("#0e0e0e"),
                ),
                ash = mapOf(
                    "c50" to color("#8d8d8d"),
                    "c100" to color("#6b6b6b"),
                    "c200" to color("#545454"),
                    "c300" to color("#3c3c3c"),
                    "c400" to color("#313131"),
                    "c500" to color("#2c2c2c"),
                    "c600" to color("#252525"),
                    "c700" to color("#1e1e1e"),
                    "c800" to color("#181818"),
                    "c900" to color("#111111"),
                ),
                blue = mapOf(
                    "c200" to color("#868686"),
                    "c300" to color("#646464"),
                    "c400" to color("#4e4e4e"),
                    "c500" to color("#383838"),
                ),
            ),
        ),
        createPaletteTheme(
            PaletteThemeSpec(
                id = "red",
                name = "Red",
                purple = mapOf(
                    "c50" to color("#feabac"),
                    "c100" to color("#fe8385"),
                    "c200" to color("#ea5b5e"),
                    "c300" to color("#d34648"),
                    "c400" to color("#bd3436"),
                    "c500" to color("#852a2b"),
                ),
                shade = mapOf(
                    "c25" to color("#b3675d"),
                    "c50" to color("#9c605c"),
                    "c100" to color("#834d49"),
                    "c200" to color("#673b38"),
                    "c300" to color("#542f2c"),
                    "c400" to color("#452422"),
                    "c500" to color("#361c1a"),
                    "c600" to color("#2b1614"),
                    "c700" to color("#241210"),
                    "c800" to color("#1c0e0d"),
                    "c900" to color("#130909"),
                ),
                ash = mapOf(
                    "c50" to color("#ac6e6f"),
                    "c100" to color("#8b4b4c"),
                    "c200" to color("#703739"),
                    "c300" to color("#572225"),
                    "c400" to color("#49191a"),
                    "c500" to color("#421617"),
                    "c600" to color("#371212"),
                    "c700" to color("#2e0e0f"),
                    "c800" to color("#230c0d"),
                    "c900" to color("#19090b"),
                ),
                blue = mapOf(
                    "c200" to color("#ae5d65"),
                    "c300" to color("#8c3b43"),
                    "c400" to color("#712a31"),
                    "c500" to color("#501f24"),
                ),
            ),
        ),
        createPaletteTheme(
            PaletteThemeSpec(
                id = "green",
                name = "Green",
                purple = mapOf(
                    "c50" to color("#91DB8B"),
                    "c100" to color("#4D9F3E"),
                    "c200" to color("#2B9A34"),
                    "c300" to color("#1C7C09"),
                    "c400" to color("#1A8A10"),
                    "c500" to color("#176D17"),
                ),
                shade = mapOf(
                    "c25" to color("#5DB35D"),
                    "c50" to color("#689067"),
                    "c100" to color("#567A52"),
                    "c200" to color("#3F603F"),
                    "c300" to color("#344F32"),
                    "c400" to color("#2C4127"),
                    "c500" to color("#1E321E"),
                    "c600" to color("#172818"),
                    "c700" to color("#152213"),
                    "c800" to color("#0F1B0F"),
                    "c900" to color("#0A120B"),
                ),
                ash = mapOf(
                    "c50" to color("#7F9B8B"),
                    "c100" to color("#5B7B65"),
                    "c200" to color("#44644F"),
                    "c300" to color("#2B4E34"),
                    "c400" to color("#20422B"),
                    "c500" to color("#1C3C23"),
                    "c600" to color("#17321D"),
                    "c700" to color("#132917"),
                    "c800" to color("#102013"),
                    "c900" to color("#0C160C"),
                ),
                blue = mapOf(
                    "c200" to color("#62AE5D"),
                    "c300" to color("#3E8C3B"),
                    "c400" to color("#235B25"),
                    "c500" to color("#1F5021"),
                ),
            ),
        ),
        createPaletteTheme(
            PaletteThemeSpec(
                id = "mocha",
                name = "Mocha",
                purple = mapOf(
                    "c50" to color("#E2AB68"),
                    "c100" to color("#B27C39"),
                    "c200" to color("#B1853F"),
                    "c300" to color("#88581D"),
                    "c400" to color("#8B5C27"),
                    "c500" to color("#905C22"),
                ),
                shade = mapOf(
                    "c25" to color("#B38F5D"),
                    "c50" to color("#907D67"),
                    "c100" to color("#7A6A52"),
                    "c200" to color("#60523F"),
                    "c300" to color("#4F4432"),
                    "c400" to color("#413727"),
                    "c500" to color("#322C1E"),
                    "c600" to color("#281E17"),
                    "c700" to color("#221D13"),
                    "c800" to color("#1B160F"),
                    "c900" to color("#120F0A"),
                ),
                ash = mapOf(
                    "c50" to color("#9B877F"),
                    "c100" to color("#7B665B"),
                    "c200" to color("#645044"),
                    "c300" to color("#4E3C2B"),
                    "c400" to color("#423420"),
                    "c500" to color("#3C2F1C"),
                    "c600" to color("#322517"),
                    "c700" to color("#292113"),
                    "c800" to color("#201910"),
                    "c900" to color("#16100C"),
                ),
                blue = mapOf(
                    "c200" to color("#987A4E"),
                    "c300" to color("#775936"),
                    "c400" to color("#785D34"),
                    "c500" to color("#534024"),
                ),
            ),
        ),
        createPaletteTheme(
            PaletteThemeSpec(
                id = "pink",
                name = "Pink",
                purple = mapOf(
                    "c50" to color("#E964E9"),
                    "c100" to color("#CE40AD"),
                    "c200" to color("#C132BC"),
                    "c300" to color("#A1117D"),
                    "c400" to color("#AE299A"),
                    "c500" to color("#98147E"),
                ),
                shade = mapOf(
                    "c25" to color("#B35DA5"),
                    "c50" to color("#906788"),
                    "c100" to color("#7A5275"),
                    "c200" to color("#603F5B"),
                    "c300" to color("#4F324D"),
                    "c400" to color("#412738"),
                    "c500" to color("#321E31"),
                    "c600" to color("#281726"),
                    "c700" to color("#211322"),
                    "c800" to color("#1B0F1A"),
                    "c900" to color("#120A11"),
                ),
                ash = mapOf(
                    "c50" to color("#9B7F95"),
                    "c100" to color("#7B5B75"),
                    "c200" to color("#64445F"),
                    "c300" to color("#4E2B48"),
                    "c400" to color("#412042"),
                    "c500" to color("#41203E"),
                    "c600" to color("#32172D"),
                    "c700" to color("#291328"),
                    "c800" to color("#1E1020"),
                    "c900" to color("#150C16"),
                ),
                blue = mapOf(
                    "c200" to color("#AE5D9C"),
                    "c300" to color("#8C3B87"),
                    "c400" to color("#5B2353"),
                    "c500" to color("#501F4C"),
                ),
            ),
        ),
        createAccentDarkTheme(
            AccentDarkThemeSpec(
                id = "acid",
                name = "Acid",
                purple = mapOf(
                    "c50" to color("#1f6e1f"),
                    "c100" to color("#1f8f1f"),
                    "c200" to color("#1fa11f"),
                    "c300" to color("#1fb31f"),
                    "c400" to color("#1fc41f"),
                    "c500" to color("#1fd61f"),
                    "c600" to color("#1aa31a"),
                ),
                previewSecondary = color("#1f6e1f"),
                lightBar = color("#021902"),
            ),
        ),
        createAccentDarkTheme(
            AccentDarkThemeSpec(
                id = "ember",
                name = "Ember",
                purple = mapOf(
                    "c50" to color("#8E2020"),
                    "c100" to color("#CF1F1F"),
                    "c200" to color("#CF1F1F"),
                    "c300" to color("#CF1F1F"),
                    "c400" to color("#CF1F1F"),
                    "c500" to color("#CF1F1F"),
                    "c600" to color("#b30000"),
                ),
                previewSecondary = color("#8E2020"),
                lightBar = color("#180101"),
            ),
        ),
        createAccentDarkTheme(
            AccentDarkThemeSpec(
                id = "spark",
                name = "Spark",
                purple = mapOf(
                    "c50" to color("#E0AC0D"),
                    "c100" to color("#CF9F11"),
                    "c200" to color("#CF9F11"),
                    "c300" to color("#CF9F11"),
                    "c400" to color("#E0AC0D"),
                    "c500" to color("#C5A00A"),
                    "c600" to color("#C5A00A"),
                ),
                previewSecondary = color("#E0AC0D"),
                lightBar = color("#201A03"),
            ),
        ),
        createAccentDarkTheme(
            AccentDarkThemeSpec(
                id = "noir",
                name = "Noir",
                purple = mapOf(
                    "c50" to color("#575757"),
                    "c100" to color("#575757"),
                    "c200" to color("#575757"),
                    "c300" to color("#575757"),
                    "c400" to color("#575757"),
                    "c500" to color("#575757"),
                    "c600" to color("#2c2c2c"),
                ),
                previewSecondary = color("#0d0d0d"),
                lightBar = color("#0e0e0e"),
            ),
        ),
        createClassicTheme(
            ClassicThemeSpec(
                id = "classic",
                name = "Classic",
                blue = mapOf(
                    "c200" to color("hsla(240, 33%, 52%, 1)"),
                    "c300" to color("hsla(240, 40%, 39%, 1)"),
                    "c400" to color("hsla(240, 46%, 30%, 1)"),
                    "c500" to color("hsla(240, 45%, 22%, 1)"),
                ),
                purple = mapOf(
                    "c50" to color("hsla(280, 100%, 83%, 1)"),
                    "c100" to color("hsla(270, 100%, 75%, 1)"),
                    "c200" to color("hsla(270, 79%, 64%, 1)"),
                    "c300" to color("hsla(270, 61%, 55%, 1)"),
                    "c400" to color("hsla(270, 59%, 47%, 1)"),
                    "c500" to color("hsla(270, 52%, 34%, 1)"),
                    "c900" to color("hsla(270, 40%, 9%, 1)"),
                ),
                ash = mapOf(
                    "c50" to color("hsla(210, 11%, 55%, 1)"),
                    "c100" to color("hsla(210, 15%, 42%, 1)"),
                    "c200" to color("hsla(210, 17%, 33%, 1)"),
                    "c300" to color("hsla(210, 29%, 24%, 1)"),
                    "c500" to color("hsla(210, 35%, 17%, 1)"),
                    "c700" to color("hsla(210, 35%, 12%, 1)"),
                ),
                shade = mapOf(
                    "c25" to color("hsla(240, 33%, 53%, 1)"),
                    "c50" to color("hsla(240, 17%, 48%, 1)"),
                    "c100" to color("hsla(240, 20%, 40%, 1)"),
                    "c200" to color("hsla(240, 20%, 31%, 1)"),
                    "c300" to color("hsla(240, 22%, 25%, 1)"),
                    "c400" to color("hsla(240, 25%, 21%, 1)"),
                    "c500" to color("hsla(240, 26%, 16%, 1)"),
                    "c600" to color("hsla(240, 31%, 12%, 1)"),
                    "c700" to color("hsla(240, 29%, 10%, 1)"),
                    "c800" to color("hsla(240, 30%, 8%, 1)"),
                    "c900" to color("hsla(240, 29%, 5%, 1)"),
                ),
                previewSecondary = color("hsla(240, 17%, 48%, 1)"),
                previewGhost = color("#FFFFFF"),
                globalAccentA = color("hsla(240, 33%, 52%, 1)"),
                lightBar = color("hsla(240, 46%, 30%, 1)"),
                mediaHoverBackground = color("hsla(240, 31%, 12%, 1)"),
                mediaHoverAccent = color("hsla(240, 33%, 53%, 1)"),
                mediaHoverShadow = color("hsla(240, 29%, 5%, 1)"),
                mediaShadow = color("hsla(240, 29%, 10%, 1)"),
            ),
        ),
        createClassicTheme(
            ClassicThemeSpec(
                id = "forest",
                name = "Forest",
                blue = mapOf(
                    "c200" to color("hsla(121, 23%, 40%, 1)"),
                    "c300" to color("hsla(123, 27%, 32%, 1)"),
                    "c400" to color("hsla(123, 28%, 25%, 1)"),
                    "c500" to color("hsla(124, 30%, 20%, 1)"),
                    "c800" to color("hsla(124, 32%, 9%, 1)"),
                ),
                purple = mapOf(
                    "c50" to color("hsla(116, 24%, 53%, 1)"),
                    "c100" to color("hsla(115, 26%, 40%, 1)"),
                    "c200" to color("hsla(119, 28%, 33%, 1)"),
                    "c300" to color("hsla(119, 31%, 26%, 1)"),
                    "c400" to color("hsla(120, 32%, 22%, 1)"),
                    "c500" to color("hsla(122, 34%, 18%, 1)"),
                ),
                ash = mapOf(
                    "c50" to color("hsla(144, 11%, 47%, 1)"),
                    "c100" to color("hsla(145, 12%, 38%, 1)"),
                    "c200" to color("hsla(146, 13%, 31%, 1)"),
                    "c300" to color("hsla(147, 15%, 24%, 1)"),
                    "c500" to color("hsla(146, 18%, 15%, 1)"),
                    "c700" to color("hsla(140, 19%, 9%, 1)"),
                ),
                shade = mapOf(
                    "c25" to color("hsla(120, 27%, 40%, 1)"),
                    "c50" to color("hsla(120, 26%, 34%, 1)"),
                    "c100" to color("hsla(120, 25%, 28%, 1)"),
                    "c200" to color("hsla(120, 25%, 23%, 1)"),
                    "c300" to color("hsla(120, 26%, 19%, 1)"),
                    "c400" to color("hsla(120, 27%, 15%, 1)"),
                    "c500" to color("hsla(120, 28%, 11%, 1)"),
                    "c600" to color("hsla(120, 29%, 9%, 1)"),
                    "c700" to color("hsla(120, 29%, 7%, 1)"),
                    "c800" to color("hsla(120, 39%, 5%, 1)"),
                    "c900" to color("hsla(120, 33%, 2%, 1)"),
                ),
                previewSecondary = color("hsla(120, 26%, 34%, 1)"),
                previewGhost = color("#FFFFFF"),
                globalAccentA = color("hsla(121, 23%, 40%, 1)"),
                lightBar = color("hsla(124, 32%, 9%, 1)"),
                mediaHoverBackground = color("hsla(120, 29%, 9%, 1)"),
                mediaHoverAccent = color("hsla(120, 27%, 40%, 1)"),
                mediaHoverShadow = color("hsla(120, 33%, 2%, 1)"),
                mediaShadow = color("hsla(120, 29%, 7%, 1)"),
            ),
        ),
        createClassicTheme(
            ClassicThemeSpec(
                id = "frost",
                name = "Frost",
                blue = mapOf(
                    "c200" to color("hsla(210, 70%, 65%, 1)"),
                    "c300" to color("hsla(210, 60%, 50%, 1)"),
                    "c400" to color("hsla(210, 50%, 40%, 1)"),
                    "c500" to color("hsla(210, 45%, 30%, 1)"),
                ),
                purple = mapOf(
                    "c50" to color("hsla(170, 40%, 75%, 1)"),
                    "c100" to color("hsla(170, 45%, 60%, 1)"),
                    "c200" to color("hsla(170, 50%, 50%, 1)"),
                    "c300" to color("hsla(170, 55%, 45%, 1)"),
                    "c400" to color("hsla(170, 60%, 40%, 1)"),
                    "c500" to color("hsla(170, 65%, 32%, 1)"),
                    "c700" to color("hsla(170, 75%, 18%, 1)"),
                    "c900" to color("hsla(170, 85%, 8%, 1)"),
                ),
                ash = mapOf(
                    "c50" to color("hsla(210, 20%, 60%, 1)"),
                    "c100" to color("hsla(210, 15%, 55%, 1)"),
                    "c200" to color("hsla(210, 10%, 35%, 1)"),
                    "c300" to color("hsla(210, 8%, 28%, 1)"),
                    "c500" to color("hsla(210, 45%, 25%, 1)"),
                    "c700" to color("hsla(210, 40%, 16%, 1)"),
                ),
                shade = mapOf(
                    "c25" to color("hsla(210, 80%, 75%, 1)"),
                    "c50" to color("hsla(210, 100%, 78%, 1)"),
                    "c100" to color("hsla(210, 80%, 65%, 1)"),
                    "c200" to color("hsla(210, 60%, 50%, 1)"),
                    "c300" to color("hsla(210, 60%, 40%, 1)"),
                    "c400" to color("hsla(210, 50%, 26%, 1)"),
                    "c500" to color("hsla(210, 25%, 27%, 1)"),
                    "c600" to color("hsla(210, 20%, 20%, 1)"),
                    "c700" to color("hsla(210, 15%, 16%, 1)"),
                    "c800" to color("hsla(210, 38%, 12%, 1)"),
                    "c900" to color("hsla(210, 35%, 8%, 1)"),
                ),
                previewSecondary = color("hsla(210, 100%, 78%, 1)"),
                previewGhost = color("hsla(170, 60%, 40%, 1)"),
                globalAccentA = color("hsla(210, 70%, 65%, 1)"),
                lightBar = color("hsla(210, 50%, 40%, 1)"),
                mediaHoverBackground = color("hsla(170, 85%, 8%, 1)"),
                mediaHoverAccent = color("hsla(210, 80%, 75%, 1)"),
                mediaHoverShadow = color("hsla(210, 35%, 8%, 1)"),
                mediaShadow = color("hsla(170, 75%, 18%, 1)"),
            ),
        ),
        createClassicTheme(
            ClassicThemeSpec(
                id = "grape",
                name = "Grape",
                blue = mapOf(
                    "c200" to color("#825eff"),
                    "c300" to color("#6541e6"),
                    "c400" to color("#4c31cc"),
                    "c500" to color("#3a24a3"),
                    "c800" to color("#180e42"),
                ),
                purple = mapOf(
                    "c50" to color("#f0b3ff"),
                    "c100" to color("#e080ff"),
                    "c200" to color("#cc4dff"),
                    "c300" to color("#b320f0"),
                    "c400" to color("#9917cc"),
                    "c500" to color("#701199"),
                ),
                ash = mapOf(
                    "c50" to color("#9b8fb1"),
                    "c100" to color("#7e7195"),
                    "c200" to color("#62577a"),
                    "c300" to color("#4a4061"),
                    "c500" to color("#30293f"),
                    "c700" to color("#1c1726"),
                ),
                shade = mapOf(
                    "c25" to color("#8a4de0"),
                    "c50" to color("#7555a8"),
                    "c100" to color("#604585"),
                    "c200" to color("#4b3666"),
                    "c300" to color("#3d2b50"),
                    "c400" to color("#312240"),
                    "c500" to color("#251931"),
                    "c600" to color("#1c1325"),
                    "c700" to color("#160f1d"),
                    "c800" to color("#110b16"),
                    "c900" to color("#0c0610"),
                ),
                previewSecondary = color("#7555a8"),
                previewGhost = color("#FFFFFF"),
                globalAccentA = color("#825eff"),
                lightBar = color("#180e42"),
                mediaHoverBackground = color("#1c1325"),
                mediaHoverAccent = color("#8a4de0"),
                mediaHoverShadow = color("#0c0610"),
                mediaShadow = color("#160f1d"),
            ),
        ),
        createClassicTheme(
            ClassicThemeSpec(
                id = "hulk",
                name = "Hulk",
                blue = mapOf(
                    "c200" to color("hsla(285, 65%, 60%, 1)"),
                    "c300" to color("hsla(285, 60%, 48%, 1)"),
                    "c400" to color("hsla(285, 55%, 38%, 1)"),
                    "c500" to color("hsla(285, 50%, 30%, 1)"),
                    "c800" to color("hsla(285, 35%, 12%, 1)"),
                ),
                purple = mapOf(
                    "c50" to color("hsla(290, 80%, 85%, 1)"),
                    "c100" to color("hsla(290, 70%, 75%, 1)"),
                    "c200" to color("hsla(290, 65%, 60%, 1)"),
                    "c300" to color("hsla(290, 60%, 48%, 1)"),
                    "c400" to color("hsla(290, 55%, 38%, 1)"),
                    "c500" to color("hsla(290, 50%, 30%, 1)"),
                ),
                ash = mapOf(
                    "c50" to color("hsla(120, 30%, 60%, 1)"),
                    "c100" to color("hsla(120, 35%, 50%, 1)"),
                    "c200" to color("hsla(120, 40%, 42%, 1)"),
                    "c300" to color("hsla(120, 45%, 32%, 1)"),
                    "c500" to color("hsla(120, 40%, 22%, 1)"),
                    "c700" to color("hsla(120, 30%, 14%, 1)"),
                ),
                shade = mapOf(
                    "c25" to color("hsla(135, 30%, 55%, 1)"),
                    "c50" to color("hsla(135, 28%, 48%, 1)"),
                    "c100" to color("hsla(135, 26%, 40%, 1)"),
                    "c200" to color("hsla(135, 24%, 32%, 1)"),
                    "c300" to color("hsla(135, 22%, 26%, 1)"),
                    "c400" to color("hsla(135, 20%, 22%, 1)"),
                    "c500" to color("hsla(135, 18%, 17%, 1)"),
                    "c600" to color("hsla(135, 17%, 13%, 1)"),
                    "c700" to color("hsla(135, 16%, 10%, 1)"),
                    "c800" to color("hsla(135, 15%, 8%, 1)"),
                    "c900" to color("hsla(135, 14%, 6%, 1)"),
                ),
                previewSecondary = color("hsla(135, 28%, 48%, 1)"),
                previewGhost = color("#FFFFFF"),
                globalAccentA = color("hsla(285, 65%, 60%, 1)"),
                lightBar = color("hsla(285, 35%, 12%, 1)"),
                mediaHoverBackground = color("hsla(135, 17%, 13%, 1)"),
                mediaHoverAccent = color("hsla(135, 30%, 55%, 1)"),
                mediaHoverShadow = color("hsla(135, 14%, 6%, 1)"),
                mediaShadow = color("hsla(135, 16%, 10%, 1)"),
            ),
        ),
        createClassicTheme(
            ClassicThemeSpec(
                id = "christmas",
                name = "Christmas",
                blue = mapOf(
                    "c200" to color("hsla(0, 50%, 50%, 1)"),
                    "c300" to color("hsla(0, 55%, 40%, 1)"),
                    "c400" to color("hsla(0, 60%, 30%, 1)"),
                    "c500" to color("hsla(0, 55%, 22%, 1)"),
                ),
                purple = mapOf(
                    "c50" to color("hsla(0, 80%, 75%, 1)"),
                    "c100" to color("hsla(0, 90%, 55%, 1)"),
                    "c200" to color("hsla(0, 85%, 45%, 1)"),
                    "c300" to color("hsla(0, 85%, 45%, 1)"),
                    "c400" to color("hsla(0, 80%, 35%, 1)"),
                    "c500" to color("hsla(0, 75%, 28%, 1)"),
                ),
                ash = mapOf(
                    "c50" to color("hsla(140, 11%, 55%, 1)"),
                    "c100" to color("hsla(140, 15%, 42%, 1)"),
                    "c200" to color("hsla(140, 17%, 33%, 1)"),
                    "c300" to color("hsla(140, 29%, 24%, 1)"),
                    "c500" to color("hsla(140, 35%, 17%, 1)"),
                    "c700" to color("hsla(140, 35%, 12%, 1)"),
                ),
                shade = mapOf(
                    "c25" to color("hsla(140, 33%, 53%, 1)"),
                    "c50" to color("hsla(140, 17%, 48%, 1)"),
                    "c100" to color("hsla(140, 20%, 40%, 1)"),
                    "c200" to color("hsla(140, 20%, 31%, 1)"),
                    "c300" to color("hsla(140, 22%, 25%, 1)"),
                    "c400" to color("hsla(140, 25%, 21%, 1)"),
                    "c500" to color("hsla(140, 26%, 16%, 1)"),
                    "c600" to color("hsla(140, 31%, 12%, 1)"),
                    "c700" to color("hsla(140, 29%, 10%, 1)"),
                    "c800" to color("hsla(140, 30%, 8%, 1)"),
                    "c900" to color("hsla(140, 29%, 5%, 1)"),
                ),
                previewSecondary = color("hsla(140, 29%, 24%, 1)"),
                previewGhost = color("#FFFFFF"),
                globalAccentA = color("hsla(140, 17%, 33%, 1)"),
                lightBar = color("hsla(0, 60%, 30%, 1)"),
                mediaHoverBackground = color("hsla(140, 31%, 12%, 1)"),
                mediaHoverAccent = color("hsla(140, 33%, 53%, 1)"),
                mediaHoverShadow = color("hsla(140, 29%, 5%, 1)"),
                mediaShadow = color("hsla(140, 29%, 10%, 1)"),
            ),
        ),
        createClassicTheme(
            ClassicThemeSpec(
                id = "wolverine",
                name = "Wolverine",
                blue = mapOf(
                    "c200" to color("hsla(220, 50%, 50%, 1)"),
                    "c300" to color("hsla(220, 55%, 40%, 1)"),
                    "c400" to color("hsla(220, 60%, 30%, 1)"),
                    "c500" to color("hsla(220, 55%, 22%, 1)"),
                ),
                purple = mapOf(
                    "c50" to color("hsla(48, 100%, 75%, 1)"),
                    "c100" to color("hsla(48, 95%, 65%, 1)"),
                    "c200" to color("hsla(46, 90%, 55%, 1)"),
                    "c300" to color("hsla(44, 85%, 45%, 1)"),
                    "c400" to color("hsla(42, 80%, 35%, 1)"),
                    "c500" to color("hsla(40, 75%, 28%, 1)"),
                ),
                ash = mapOf(
                    "c50" to color("hsla(210, 11%, 55%, 1)"),
                    "c100" to color("hsla(210, 15%, 42%, 1)"),
                    "c200" to color("hsla(210, 17%, 33%, 1)"),
                    "c300" to color("hsla(210, 29%, 24%, 1)"),
                    "c500" to color("hsla(210, 35%, 17%, 1)"),
                    "c700" to color("hsla(210, 35%, 12%, 1)"),
                ),
                shade = mapOf(
                    "c25" to color("hsla(240, 33%, 53%, 1)"),
                    "c50" to color("hsla(240, 17%, 48%, 1)"),
                    "c100" to color("hsla(240, 20%, 40%, 1)"),
                    "c200" to color("hsla(240, 20%, 31%, 1)"),
                    "c300" to color("hsla(240, 22%, 25%, 1)"),
                    "c400" to color("hsla(240, 25%, 21%, 1)"),
                    "c500" to color("hsla(240, 26%, 16%, 1)"),
                    "c600" to color("hsla(240, 31%, 12%, 1)"),
                    "c700" to color("hsla(240, 29%, 10%, 1)"),
                    "c800" to color("hsla(240, 30%, 8%, 1)"),
                    "c900" to color("hsla(240, 29%, 5%, 1)"),
                ),
                previewSecondary = color("hsla(44, 85%, 45%, 1)"),
                previewGhost = color("#FFFFFF"),
                globalAccentA = color("hsla(220, 50%, 50%, 1)"),
                lightBar = color("hsla(220, 60%, 30%, 1)"),
                mediaHoverBackground = color("hsla(240, 31%, 12%, 1)"),
                mediaHoverAccent = color("hsla(240, 33%, 53%, 1)"),
                mediaHoverShadow = color("hsla(240, 29%, 5%, 1)"),
                mediaShadow = color("hsla(240, 29%, 10%, 1)"),
            ),
        ),
        createClassicTheme(
            ClassicThemeSpec(
                id = "spiderman",
                name = "Spiderman",
                blue = mapOf(
                    "c200" to color("hsla(220, 60%, 55%, 1)"),
                    "c300" to color("hsla(220, 65%, 42%, 1)"),
                    "c500" to color("hsla(220, 65%, 25%, 1)"),
                    "c800" to color("hsla(220, 40%, 10%, 1)"),
                ),
                purple = mapOf(
                    "c50" to color("hsla(220, 80%, 80%, 1)"),
                    "c100" to color("hsla(220, 65%, 68%, 1)"),
                    "c200" to color("hsla(220, 60%, 55%, 1)"),
                    "c300" to color("hsla(220, 65%, 42%, 1)"),
                    "c400" to color("hsla(220, 70%, 32%, 1)"),
                    "c500" to color("hsla(220, 65%, 25%, 1)"),
                ),
                ash = mapOf(
                    "c50" to color("hsla(0, 60%, 60%, 1)"),
                    "c100" to color("hsla(0, 60%, 50%, 1)"),
                    "c200" to color("hsla(0, 65%, 42%, 1)"),
                    "c300" to color("hsla(0, 70%, 32%, 1)"),
                    "c500" to color("hsla(0, 60%, 22%, 1)"),
                    "c700" to color("hsla(0, 45%, 14%, 1)"),
                ),
                shade = mapOf(
                    "c25" to color("hsla(0, 55%, 55%, 1)"),
                    "c50" to color("hsla(0, 50%, 48%, 1)"),
                    "c100" to color("hsla(0, 45%, 40%, 1)"),
                    "c200" to color("hsla(0, 40%, 31%, 1)"),
                    "c300" to color("hsla(0, 38%, 25%, 1)"),
                    "c400" to color("hsla(0, 35%, 21%, 1)"),
                    "c500" to color("hsla(0, 32%, 16%, 1)"),
                    "c600" to color("hsla(0, 30%, 12%, 1)"),
                    "c700" to color("hsla(0, 28%, 10%, 1)"),
                    "c800" to color("hsla(0, 26%, 8%, 1)"),
                    "c900" to color("hsla(0, 24%, 5%, 1)"),
                ),
                previewSecondary = color("hsla(0, 50%, 48%, 1)"),
                previewGhost = color("#FFFFFF"),
                globalAccentA = color("hsla(220, 60%, 55%, 1)"),
                lightBar = color("hsla(220, 40%, 10%, 1)"),
                mediaHoverBackground = color("hsla(0, 30%, 12%, 1)"),
                mediaHoverAccent = color("hsla(0, 55%, 55%, 1)"),
                mediaHoverShadow = color("hsla(0, 24%, 5%, 1)"),
                mediaShadow = color("hsla(0, 28%, 10%, 1)"),
            ),
        ),
        createClassicTheme(
            ClassicThemeSpec(
                id = "autumn",
                name = "Autumn",
                blue = mapOf(
                    "c200" to color("hsla(25, 70%, 60%, 1)"),
                    "c300" to color("hsla(25, 60%, 45%, 1)"),
                    "c400" to color("hsla(25, 50%, 35%, 1)"),
                    "c500" to color("hsla(25, 45%, 25%, 1)"),
                ),
                purple = mapOf(
                    "c50" to color("hsla(15, 100%, 75%, 1)"),
                    "c100" to color("hsla(15, 100%, 60%, 1)"),
                    "c200" to color("hsla(15, 90%, 50%, 1)"),
                    "c300" to color("hsla(15, 80%, 45%, 1)"),
                    "c400" to color("hsla(15, 75%, 40%, 1)"),
                    "c500" to color("hsla(15, 70%, 32%, 1)"),
                    "c700" to color("hsla(15, 60%, 18%, 1)"),
                    "c900" to color("hsla(15, 50%, 8%, 1)"),
                ),
                ash = mapOf(
                    "c50" to color("hsla(45, 39%, 60%, 1)"),
                    "c100" to color("hsla(45, 24%, 55%, 1)"),
                    "c200" to color("hsla(45, 10%, 35%, 1)"),
                    "c300" to color("hsla(45, 8%, 28%, 1)"),
                    "c500" to color("hsla(25, 45%, 25%, 1)"),
                    "c700" to color("hsla(25, 40%, 16%, 1)"),
                ),
                shade = mapOf(
                    "c25" to color("hsla(24, 80%, 70%, 1)"),
                    "c50" to color("hsla(25, 100%, 72%, 1)"),
                    "c100" to color("hsla(25, 80%, 60%, 1)"),
                    "c200" to color("hsla(25, 60%, 45%, 1)"),
                    "c300" to color("hsla(25, 60%, 35%, 1)"),
                    "c400" to color("hsla(25, 50%, 21%, 1)"),
                    "c500" to color("hsla(35, 25%, 22%, 1)"),
                    "c600" to color("hsla(45, 20%, 16%, 1)"),
                    "c700" to color("hsla(60, 15%, 12%, 1)"),
                    "c800" to color("hsla(25, 38%, 8%, 1)"),
                    "c900" to color("hsla(25, 35%, 5%, 1)"),
                ),
                previewSecondary = color("hsla(25, 100%, 72%, 1)"),
                previewGhost = color("hsla(15, 75%, 40%, 1)"),
                globalAccentA = color("hsla(25, 70%, 60%, 1)"),
                lightBar = color("hsla(25, 50%, 35%, 1)"),
                mediaHoverBackground = color("hsla(15, 50%, 8%, 1)"),
                mediaHoverAccent = color("hsla(25, 80%, 70%, 1)"),
                mediaHoverShadow = color("hsla(25, 35%, 5%, 1)"),
                mediaShadow = color("hsla(15, 60%, 18%, 1)"),
            ),
        ),
        createAccentDarkTheme(
            AccentDarkThemeSpec(
                id = "cobalt",
                name = "Cobalt",
                purple = mapOf(
                    "c50" to color("#80EAFF"),
                    "c100" to color("#43DFFF"),
                    "c200" to color("#00D4FF"),
                    "c300" to color("#00B6E6"),
                    "c400" to color("#0099CC"),
                    "c500" to color("#007CAD"),
                    "c600" to color("#00668F"),
                ),
                previewSecondary = color("#0099CC"),
                lightBar = color("#00384D"),
            ),
        ),
        createClassicTheme(
            ClassicThemeSpec(
                id = "popsicle",
                name = "Popsicle",
                blue = mapOf(
                    "c200" to color("hsla(200, 70%, 60%, 1)"),
                    "c300" to color("hsla(200, 60%, 45%, 1)"),
                    "c400" to color("hsla(200, 50%, 35%, 1)"),
                    "c500" to color("hsla(200, 45%, 25%, 1)"),
                ),
                purple = mapOf(
                    "c50" to color("hsla(280, 100%, 85%, 1)"),
                    "c100" to color("hsla(300, 100%, 75%, 1)"),
                    "c200" to color("hsla(300, 80%, 65%, 1)"),
                    "c300" to color("hsla(310, 65%, 55%, 1)"),
                    "c400" to color("hsla(320, 60%, 47%, 1)"),
                    "c500" to color("hsla(325, 50%, 36%, 1)"),
                ),
                ash = mapOf(
                    "c50" to color("hsla(60, 8%, 60%, 1)"),
                    "c100" to color("hsla(60, 10%, 45%, 1)"),
                    "c200" to color("hsla(60, 11%, 35%, 1)"),
                    "c300" to color("hsla(60, 12%, 28%, 1)"),
                    "c500" to color("hsla(200, 45%, 25%, 1)"),
                    "c700" to color("hsla(200, 40%, 16%, 1)"),
                ),
                shade = mapOf(
                    "c25" to color("hsla(0, 80%, 70%, 1)"),
                    "c50" to color("hsla(30, 100%, 72%, 1)"),
                    "c100" to color("hsla(30, 80%, 60%, 1)"),
                    "c200" to color("hsla(200, 60%, 45%, 1)"),
                    "c300" to color("hsla(30, 60%, 35%, 1)"),
                    "c400" to color("hsla(200, 50%, 35%, 1)"),
                    "c500" to color("hsla(30, 50%, 21%, 1)"),
                    "c600" to color("hsla(30, 45%, 16%, 1)"),
                    "c700" to color("hsla(30, 40%, 12%, 1)"),
                    "c800" to color("hsla(30, 38%, 9%, 1)"),
                    "c900" to color("hsla(30, 35%, 6%, 1)"),
                ),
                previewSecondary = color("hsla(30, 100%, 72%, 1)"),
                previewGhost = color("hsla(320, 60%, 47%, 1)"),
                globalAccentA = color("hsla(200, 70%, 60%, 1)"),
                lightBar = color("hsla(200, 50%, 35%, 1)"),
                mediaHoverBackground = color("hsla(30, 45%, 16%, 1)"),
                mediaHoverAccent = color("hsla(0, 80%, 70%, 1)"),
                mediaHoverShadow = color("hsla(30, 35%, 6%, 1)"),
                mediaShadow = color("hsla(30, 40%, 12%, 1)"),
            ),
        ),
    )
}

private fun createPaletteTheme(spec: PaletteThemeSpec): ZStreamTheme {
    val base = DefaultTheme.create()
    return base.copy(
        id = spec.id,
        name = spec.name,
        colors = base.colors.copy(
            themePreview = ThemePreview(
                primary = spec.blue.getValue("c200"),
                secondary = spec.shade.getValue("c50"),
                ghost = base.colors.themePreview.ghost,
            ),
            pill = Pill(
                background = spec.shade.getValue("c300"),
                backgroundHover = spec.shade.getValue("c200"),
                highlight = spec.blue.getValue("c200"),
                activeBackground = spec.shade.getValue("c300"),
            ),
            global = Global(
                accentA = spec.blue.getValue("c200"),
                accentB = spec.blue.getValue("c300"),
            ),
            lightBar = LightBar(light = spec.blue.getValue("c400")),
            buttons = Buttons(
                toggle = spec.purple.getValue("c300"),
                toggleDisabled = spec.ash.getValue("c500"),
                danger = base.colors.buttons.danger,
                dangerHover = base.colors.buttons.dangerHover,
                secondary = spec.ash.getValue("c700"),
                secondaryText = base.colors.buttons.secondaryText,
                secondaryHover = spec.ash.getValue("c700"),
                primary = base.colors.buttons.primary,
                primaryText = base.colors.buttons.primaryText,
                primaryHover = base.colors.buttons.primaryHover,
                purple = spec.purple.getValue("c500"),
                purpleHover = spec.purple.getValue("c400"),
                cancel = spec.ash.getValue("c500"),
                cancelHover = spec.ash.getValue("c300"),
            ),
            background = Background(
                main = spec.shade.getValue("c900"),
                secondary = spec.shade.getValue("c600"),
                secondaryHover = spec.shade.getValue("c400"),
                accentA = spec.purple.getValue("c500"),
                accentB = spec.blue.getValue("c500"),
            ),
            modal = Modal(background = spec.shade.getValue("c800")),
            type = Type(
                logo = spec.purple.getValue("c100"),
                emphasis = base.colors.type.emphasis,
                text = spec.shade.getValue("c50"),
                dimmed = spec.shade.getValue("c50"),
                divider = spec.ash.getValue("c500"),
                secondary = spec.ash.getValue("c100"),
                danger = base.colors.type.danger,
                success = base.colors.type.success,
                link = spec.purple.getValue("c100"),
                linkHover = spec.purple.getValue("c50"),
            ),
            search = Search(
                background = spec.shade.getValue("c500"),
                hoverBackground = spec.shade.getValue("c600"),
                focused = spec.shade.getValue("c400"),
                placeholder = spec.shade.getValue("c100"),
                icon = spec.shade.getValue("c100"),
                text = base.colors.search.text,
            ),
            mediaCard = MediaCard(
                hoverBackground = spec.shade.getValue("c600"),
                hoverAccent = spec.shade.getValue("c25"),
                hoverShadow = spec.shade.getValue("c900"),
                shadow = spec.shade.getValue("c700"),
                barColor = spec.ash.getValue("c200"),
                barFillColor = spec.purple.getValue("c100"),
                badge = spec.shade.getValue("c700"),
                badgeText = spec.ash.getValue("c100"),
            ),
            largeCard = LargeCard(
                background = spec.shade.getValue("c600"),
                icon = spec.purple.getValue("c400"),
            ),
            dropdown = Dropdown(
                background = spec.shade.getValue("c600"),
                altBackground = spec.shade.getValue("c700"),
                hoverBackground = spec.shade.getValue("c500"),
                highlight = base.colors.dropdown.highlight,
                highlightHover = base.colors.dropdown.highlightHover,
                text = spec.shade.getValue("c50"),
                secondary = spec.shade.getValue("c100"),
                border = spec.shade.getValue("c400"),
                contentBackground = spec.shade.getValue("c500"),
            ),
            authentication = Authentication(
                border = spec.shade.getValue("c300"),
                inputBg = spec.shade.getValue("c600"),
                inputBgHover = spec.shade.getValue("c500"),
                wordBackground = spec.shade.getValue("c500"),
                copyText = spec.shade.getValue("c100"),
                copyTextHover = spec.ash.getValue("c50"),
                errorText = base.colors.authentication.errorText,
            ),
            settings = Settings(
                sidebar = SettingsSidebar(
                    activeLink = spec.shade.getValue("c600"),
                    badge = spec.shade.getValue("c900"),
                    type = SettingsSidebarType(
                        secondary = spec.shade.getValue("c200"),
                        inactive = spec.shade.getValue("c50"),
                        icon = spec.shade.getValue("c50"),
                        iconActivated = spec.purple.getValue("c200"),
                        activated = spec.purple.getValue("c50"),
                    ),
                ),
                card = SettingsCard(
                    border = spec.shade.getValue("c400"),
                    background = spec.shade.getValue("c400"),
                    altBackground = spec.shade.getValue("c400"),
                ),
                saveBar = SettingsSaveBar(background = spec.shade.getValue("c800")),
            ),
            utils = Utils(divider = spec.ash.getValue("c300")),
            errors = Errors(
                card = spec.shade.getValue("c800"),
                border = spec.ash.getValue("c500"),
                type = ErrorsType(secondary = spec.ash.getValue("c100")),
            ),
            about = About(
                circle = spec.ash.getValue("c500"),
                circleText = spec.ash.getValue("c50"),
            ),
            editBadge = EditBadge(
                bg = spec.ash.getValue("c500"),
                bgHover = spec.ash.getValue("c400"),
                text = spec.ash.getValue("c50"),
            ),
            progress = Progress(
                background = spec.ash.getValue("c50"),
                preloaded = spec.ash.getValue("c50"),
                filled = spec.purple.getValue("c200"),
            ),
            video = Video(
                buttonBackground = spec.ash.getValue("c200"),
                autoPlay = VideoAutoPlay(
                    background = spec.ash.getValue("c700"),
                    hover = spec.ash.getValue("c500"),
                ),
                scraping = VideoScraping(
                    card = spec.shade.getValue("c700"),
                    error = base.colors.video.scraping.error,
                    success = base.colors.video.scraping.success,
                    loading = spec.purple.getValue("c200"),
                    noresult = spec.ash.getValue("c100"),
                ),
                audio = VideoAudio(set = spec.purple.getValue("c200")),
                context = VideoContext(
                    background = spec.ash.getValue("c900"),
                    light = spec.shade.getValue("c50"),
                    border = spec.ash.getValue("c600"),
                    hoverColor = spec.ash.getValue("c600"),
                    buttonFocus = spec.ash.getValue("c500"),
                    flagBg = spec.ash.getValue("c500"),
                    inputBg = spec.ash.getValue("c600"),
                    buttonOverInputHover = spec.ash.getValue("c500"),
                    inputPlaceholder = spec.ash.getValue("c200"),
                    cardBorder = spec.ash.getValue("c700"),
                    slider = spec.ash.getValue("c50"),
                    sliderFilled = spec.purple.getValue("c200"),
                    error = base.colors.video.context.error,
                    buttons = VideoContextButtons(
                        list = spec.ash.getValue("c700"),
                        active = spec.ash.getValue("c900"),
                    ),
                    closeHover = spec.ash.getValue("c800"),
                    type = VideoContextType(
                        main = base.colors.video.context.type.main,
                        secondary = spec.ash.getValue("c200"),
                        accent = spec.purple.getValue("c200"),
                    ),
                ),
            ),
        ),
    )
}

private fun createAccentDarkTheme(spec: AccentDarkThemeSpec): ZStreamTheme {
    val base = DefaultTheme.create()
    return base.copy(
        id = spec.id,
        name = spec.name,
        colors = base.colors.copy(
            themePreview = ThemePreview(
                primary = color("#080808"),
                secondary = spec.previewSecondary,
                ghost = base.colors.themePreview.ghost,
            ),
            lightBar = LightBar(light = spec.lightBar),
            buttons = base.colors.buttons.copy(
                toggle = spec.purple.getValue("c300"),
                purple = spec.purple.getValue("c600"),
                purpleHover = spec.purple.getValue("c400"),
            ),
            background = base.colors.background.copy(
                accentA = spec.purple.getValue("c600"),
            ),
            type = base.colors.type.copy(
                logo = spec.purple.getValue("c100"),
                link = spec.purple.getValue("c100"),
                linkHover = spec.purple.getValue("c50"),
            ),
            largeCard = base.colors.largeCard.copy(
                icon = spec.purple.getValue("c400"),
            ),
            settings = base.colors.settings.copy(
                sidebar = base.colors.settings.sidebar.copy(
                    type = base.colors.settings.sidebar.type.copy(
                        iconActivated = spec.purple.getValue("c200"),
                        activated = spec.purple.getValue("c100"),
                    ),
                ),
            ),
            progress = base.colors.progress.copy(
                filled = spec.purple.getValue("c200"),
            ),
            video = base.colors.video.copy(
                scraping = base.colors.video.scraping.copy(
                    loading = spec.purple.getValue("c200"),
                ),
                audio = base.colors.video.audio.copy(
                    set = spec.purple.getValue("c200"),
                ),
                context = base.colors.video.context.copy(
                    sliderFilled = spec.purple.getValue("c200"),
                    type = base.colors.video.context.type.copy(
                        accent = spec.purple.getValue("c200"),
                    ),
                ),
            ),
        ),
    )
}

private fun createClassicTheme(spec: ClassicThemeSpec): ZStreamTheme {
    val base = DefaultTheme.create()
    return base.copy(
        id = spec.id,
        name = spec.name,
        colors = base.colors.copy(
            themePreview = ThemePreview(
                primary = spec.blue.getValue("c200"),
                secondary = spec.previewSecondary,
                ghost = spec.previewGhost,
            ),
            pill = Pill(
                background = spec.shade.getValue("c300"),
                backgroundHover = spec.shade.getValue("c200"),
                highlight = spec.blue.getValue("c200"),
                activeBackground = spec.shade.getValue("c300"),
            ),
            global = Global(
                accentA = spec.globalAccentA,
                accentB = spec.blue.getValue("c300"),
            ),
            lightBar = LightBar(light = spec.lightBar),
            buttons = base.colors.buttons.copy(
                toggle = spec.purple.getValue("c300"),
                secondary = spec.ash.getValue("c700"),
                secondaryHover = spec.ash.getValue("c700"),
                purple = spec.purple.getValue("c500"),
                purpleHover = spec.purple.getValue("c400"),
                cancel = spec.ash.getValue("c500"),
                cancelHover = spec.ash.getValue("c300"),
            ),
            background = Background(
                main = spec.shade.getValue("c900"),
                secondary = spec.shade.getValue("c600"),
                secondaryHover = spec.shade.getValue("c400"),
                accentA = spec.purple.getValue("c500"),
                accentB = spec.blue.getValue("c500"),
            ),
            modal = Modal(background = spec.shade.getValue("c800")),
            type = base.colors.type.copy(
                logo = spec.purple.getValue("c100"),
                text = spec.shade.getValue("c50"),
                dimmed = spec.shade.getValue("c50"),
                divider = spec.ash.getValue("c500"),
                secondary = spec.ash.getValue("c100"),
                link = spec.purple.getValue("c100"),
                linkHover = spec.purple.getValue("c50"),
            ),
            search = base.colors.search.copy(
                background = spec.shade.getValue("c500"),
                hoverBackground = spec.shade.getValue("c600"),
                focused = spec.shade.getValue("c400"),
                placeholder = spec.shade.getValue("c100"),
                icon = spec.shade.getValue("c100"),
            ),
            mediaCard = MediaCard(
                hoverBackground = spec.mediaHoverBackground,
                hoverAccent = spec.mediaHoverAccent,
                hoverShadow = spec.mediaHoverShadow,
                shadow = spec.mediaShadow,
                barColor = spec.ash.getValue("c200"),
                barFillColor = spec.purple.getValue("c100"),
                badge = spec.shade.getValue("c700"),
                badgeText = spec.ash.getValue("c100"),
            ),
            largeCard = LargeCard(
                background = spec.shade.getValue("c600"),
                icon = spec.purple.getValue("c400"),
            ),
            dropdown = base.colors.dropdown.copy(
                background = spec.shade.getValue("c600"),
                altBackground = spec.shade.getValue("c700"),
                hoverBackground = spec.shade.getValue("c500"),
                text = spec.shade.getValue("c50"),
                secondary = spec.shade.getValue("c100"),
                border = spec.shade.getValue("c400"),
                contentBackground = spec.shade.getValue("c500"),
            ),
            authentication = base.colors.authentication.copy(
                border = spec.shade.getValue("c300"),
                inputBg = spec.shade.getValue("c600"),
                inputBgHover = spec.shade.getValue("c500"),
                wordBackground = spec.shade.getValue("c500"),
                copyText = spec.shade.getValue("c100"),
                copyTextHover = spec.ash.getValue("c50"),
            ),
            settings = Settings(
                sidebar = SettingsSidebar(
                    activeLink = spec.shade.getValue("c600"),
                    badge = spec.shade.getValue("c900"),
                    type = SettingsSidebarType(
                        secondary = spec.shade.getValue("c200"),
                        inactive = spec.shade.getValue("c50"),
                        icon = spec.shade.getValue("c50"),
                        iconActivated = spec.purple.getValue("c200"),
                        activated = spec.purple.getValue("c50"),
                    ),
                ),
                card = SettingsCard(
                    border = spec.shade.getValue("c400"),
                    background = spec.shade.getValue("c400"),
                    altBackground = spec.shade.getValue("c400"),
                ),
                saveBar = SettingsSaveBar(background = spec.shade.getValue("c800")),
            ),
            utils = Utils(divider = spec.ash.getValue("c300")),
            onboarding = Onboarding(
                bar = spec.shade.getValue("c400"),
                barFilled = spec.purple.getValue("c300"),
                divider = spec.shade.getValue("c200"),
                card = spec.shade.getValue("c800"),
                cardHover = spec.shade.getValue("c700"),
                border = spec.shade.getValue("c600"),
                good = spec.purple.getValue("c100"),
                best = base.colors.onboarding.best,
                link = spec.purple.getValue("c100"),
            ),
            errors = Errors(
                card = spec.shade.getValue("c800"),
                border = spec.ash.getValue("c500"),
                type = ErrorsType(secondary = spec.ash.getValue("c100")),
            ),
            about = About(
                circle = spec.ash.getValue("c500"),
                circleText = spec.ash.getValue("c50"),
            ),
            editBadge = EditBadge(
                bg = spec.ash.getValue("c500"),
                bgHover = spec.ash.getValue("c400", spec.ash.getValue("c500")),
                text = spec.ash.getValue("c50"),
            ),
            progress = Progress(
                background = spec.ash.getValue("c50"),
                preloaded = spec.ash.getValue("c50"),
                filled = spec.purple.getValue("c200"),
            ),
            video = Video(
                buttonBackground = spec.ash.getValue("c200"),
                autoPlay = VideoAutoPlay(
                    background = spec.ash.getValue("c700"),
                    hover = spec.ash.getValue("c500"),
                ),
                scraping = VideoScraping(
                    card = spec.shade.getValue("c700"),
                    error = base.colors.video.scraping.error,
                    success = base.colors.video.scraping.success,
                    loading = spec.purple.getValue("c200"),
                    noresult = spec.ash.getValue("c100"),
                ),
                audio = VideoAudio(set = spec.purple.getValue("c200")),
                context = VideoContext(
                    background = spec.ash.getValue("c900", spec.shade.getValue("c900")),
                    light = spec.shade.getValue("c50"),
                    border = spec.ash.getValue("c600", spec.ash.getValue("c500")),
                    hoverColor = spec.ash.getValue("c600", spec.ash.getValue("c500")),
                    buttonFocus = spec.ash.getValue("c500"),
                    flagBg = spec.ash.getValue("c500"),
                    inputBg = spec.ash.getValue("c600", spec.ash.getValue("c500")),
                    buttonOverInputHover = spec.ash.getValue("c500"),
                    inputPlaceholder = spec.ash.getValue("c200"),
                    cardBorder = spec.ash.getValue("c700"),
                    slider = spec.ash.getValue("c50"),
                    sliderFilled = spec.purple.getValue("c200"),
                    error = base.colors.video.context.error,
                    buttons = VideoContextButtons(
                        list = spec.ash.getValue("c700"),
                        active = spec.ash.getValue("c900", spec.shade.getValue("c900")),
                    ),
                    closeHover = spec.ash.getValue("c800", spec.ash.getValue("c700")),
                    type = VideoContextType(
                        main = base.colors.video.context.type.main,
                        secondary = spec.ash.getValue("c200"),
                        accent = spec.purple.getValue("c200"),
                    ),
                ),
            ),
        ),
    )
}

private fun Map<String, Color>.getValue(key: String, fallback: Color): Color = get(key) ?: fallback

private fun color(value: String): Color {
    return if (value.startsWith("hsl")) hslaColor(value) else Color(android.graphics.Color.parseColor(value))
}

private fun hslaColor(value: String): Color {
    val match = Regex("""hsla?\(\s*([-.\d]+)\s*,\s*([-.\d]+)%\s*,\s*([-.\d]+)%\s*(?:,\s*([-.\d]+)\s*)?\)""")
        .matchEntire(value)
        ?: error("Unsupported color format: $value")
    val hue = ((match.groupValues[1].toFloat() % 360f) + 360f) % 360f
    val saturation = (match.groupValues[2].toFloat() / 100f).coerceIn(0f, 1f)
    val lightness = (match.groupValues[3].toFloat() / 100f).coerceIn(0f, 1f)
    val alpha = match.groupValues.getOrNull(4)?.takeIf { it.isNotBlank() }?.toFloat()?.coerceIn(0f, 1f) ?: 1f

    val chroma = (1f - kotlin.math.abs(2f * lightness - 1f)) * saturation
    val huePrime = hue / 60f
    val x = chroma * (1f - kotlin.math.abs(huePrime % 2f - 1f))
    val (r1, g1, b1) = when {
        huePrime < 1f -> floatArrayOf(chroma, x, 0f)
        huePrime < 2f -> floatArrayOf(x, chroma, 0f)
        huePrime < 3f -> floatArrayOf(0f, chroma, x)
        huePrime < 4f -> floatArrayOf(0f, x, chroma)
        huePrime < 5f -> floatArrayOf(x, 0f, chroma)
        else -> floatArrayOf(chroma, 0f, x)
    }
    val m = lightness - chroma / 2f
    return Color(
        red = (r1 + m).coerceIn(0f, 1f),
        green = (g1 + m).coerceIn(0f, 1f),
        blue = (b1 + m).coerceIn(0f, 1f),
        alpha = alpha,
    )
}
